export const CHARACTER_MOVE = 'CHARACTER_MOVE';
export const GET_ROOM_LAYOUT = 'GET_ROOM_LAYOUT';
export const GET_FOG  = 'GET_FOG';
export const PROPOSE_POSITION = 'PROPOSE_POSITION';
export const UPDATE_PICKUP = 'UPDATE_PICKUP';
export const UPDATE_ATTACK = 'UPDATE_ATTACK';